# Generated by Django 3.2.3 on 2021-05-26 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Придумайте краткое и ёмкое название для группы сообщений', max_length=200, verbose_name='название группы')),
                ('slug', models.SlugField(help_text='Краткое, уникальное слово, которое будет видно в ссылке на страницу группы (часть URL)', max_length=100, unique=True, verbose_name='url group')),
                ('description', models.TextField(help_text='Опишите группу так, чтобы пользователь мог легко  определиться с выбором группы для сообщения.', verbose_name='описание')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'Группа',
                'db_table': 'posts_group',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ForeignKey(help_text='Пользователь, который подписывается.', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='подписчик')),
                ('user', models.ForeignKey(help_text='Пользователь, на которого подписываются.', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Группа сообщений.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_posts', to='api.group', verbose_name='группа'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique user_following'),
        ),
    ]
