# Generated by Django 3.2.3 on 2021-05-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210526_1934'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique user_following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_user_following'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('slug', 'title'), name='unique_slug'),
        ),
    ]
