# Generated by Django 3.2.3 on 2021-05-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Группа'},
        ),
    ]
