# Generated by Django 3.2.3 on 2021-05-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_group_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Группа сообщений.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_posts', to='api.group', verbose_name='группа'),
        ),
    ]
