# Generated by Django 3.2.3 on 2021-05-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-following',), 'verbose_name': 'follow', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
    ]
