# Generated by Django 3.2.3 on 2021-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210526_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique user_following'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
    ]
