# Generated by Django 3.2.3 on 2021-05-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210526_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('posts', 'group'), name='unique posts_group'),
        ),
        migrations.AlterModelTable(
            name='group',
            table=None,
        ),
    ]
