# Generated by Django 3.2.3 on 2021-05-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210527_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, help_text='Опишите группу так, чтобы пользователь мог легко  определиться с выбором группы для сообщения.', null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, help_text='Краткое, уникальное слово, которое будет видно в ссылке на страницу группы (часть URL)', max_length=100, null=True, verbose_name='url group'),
        ),
    ]
