# Generated by Django 3.2.3 on 2021-05-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210526_1834'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='group',
            name='unique posts_group',
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique slug'),
        ),
    ]
