# Generated by Django 3.2.3 on 2021-05-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210526_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'group', 'verbose_name_plural': 'Группа'},
        ),
        migrations.AlterModelTable(
            name='group',
            table='posts_group',
        ),
    ]
