# Generated by Django 3.2.3 on 2021-05-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210526_1836'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='group',
            name='unique slug',
        ),
    ]
